In [1]:
import pandas as pd
import numpy as np 


df = pd.read_pickle('C:/Users/Rafael/OneDrive/Documentos/TCC Rafaela/Dados/Pickle/cancer_mama_regiao_sudeste_com_desfecho.pickle')

In [2]:
# Pivot da Tabela para pegar max e min da idade
pivot_table = pd.pivot_table(data=df,
                             index='AP_CNSPCN',
                             values=['AP_DTINIC', 'AP_NUIDADE'],
                             aggfunc=['min','max'])

#Renomeação das colunas
pivot_table = pivot_table.set_axis(['AP_DTINIC_min', 'idade_inicial', 'AP_DTINIC_max', 'idade_max'], axis=1)

#Merge com o dataset
df = pd.merge(df, pivot_table, on='AP_CNSPCN', how='left')
df.head()

,AP_PRIPAL,AP_UFMUN,AP_CNSPCN,AP_NUIDADE,AP_SEXO,AP_RACACOR,AP_MUNPCN,AP_UFNACIO,AP_DTINIC,AP_DTFIM,...,fim,estadiamento_fim,dif_estadiamento,total_tratamentos,procedimento_inicial,desfecho,AP_DTINIC_min,idade_inicial,AP_DTINIC_max,idade_max
0,304050040,ES,âäâ{Ç{{{{üé}Çüü,40,F,99,ES,Brasil,01/01/2008,31/03/2008,...,29/01/2013,4,3,4,304020133,Piora,01/01/2008,40,29/01/2013,49
1,304050121,ES,}{{éüâ}â{Ç{{{~,61,F,99,ES,Brasil,01/01/2008,31/03/2008,...,01/10/2008,2,0,1,304050121,Alta,01/01/2008,61,01/10/2008,63
2,304050105,ES,âäâ{{{|{~ü}~ü,71,F,99,ES,Brasil,01/01/2008,31/03/2008,...,03/01/2012,2,0,2,304050105,Alta,01/01/2008,71,03/01/2012,75
3,304050121,ES,âäâ{{{|{~é{Ç~â,51,F,99,ES,Brasil,01/01/2008,31/03/2008,...,01/10/2010,2,0,1,304050121,Alta,01/01/2008,51,01/10/2010,54
4,304050113,ES,âäâ{Ç{{|}{ääÇ,40,F,99,ES,Brasil,01/01/2008,31/03/2008,...,01/10/2010,3,0,1,304050113,Alta,01/01/2008,40,01/10/2010,43

In [3]:
# Excluindo as colunas 
df.drop(columns=['AP_DTINIC_min',	'AP_DTINIC_max'], inplace=True)

df.head()

,AP_PRIPAL,AP_UFMUN,AP_CNSPCN,AP_NUIDADE,AP_SEXO,AP_RACACOR,AP_MUNPCN,AP_UFNACIO,AP_DTINIC,AP_DTFIM,...,inicio,estadiamento_inicio,fim,estadiamento_fim,dif_estadiamento,total_tratamentos,procedimento_inicial,desfecho,idade_inicial,idade_max
0,304050040,ES,âäâ{Ç{{{{üé}Çüü,40,F,99,ES,Brasil,01/01/2008,31/03/2008,...,01/01/2008,1,29/01/2013,4,3,4,304020133,Piora,40,49
1,304050121,ES,}{{éüâ}â{Ç{{{~,61,F,99,ES,Brasil,01/01/2008,31/03/2008,...,01/01/2008,2,01/10/2008,2,0,1,304050121,Alta,61,63
2,304050105,ES,âäâ{{{|{~ü}~ü,71,F,99,ES,Brasil,01/01/2008,31/03/2008,...,01/01/2008,2,03/01/2012,2,0,2,304050105,Alta,71,75
3,304050121,ES,âäâ{{{|{~é{Ç~â,51,F,99,ES,Brasil,01/01/2008,31/03/2008,...,01/01/2008,2,01/10/2010,2,0,1,304050121,Alta,51,54
4,304050113,ES,âäâ{Ç{{|}{ääÇ,40,F,99,ES,Brasil,01/01/2008,31/03/2008,...,01/01/2008,3,01/10/2010,3,0,1,304050113,Alta,40,43

In [6]:
def ajustar_idade(row):
    # Converter as colunas de string para datetime
    data_max = pd.to_datetime(row['fim'])
    data_inicial = pd.to_datetime(row['inicio'])

    # Calcular a diferença em anos
    anos_diff = (data_max - data_inicial).days // 365
    
    # Ajustar a idade se necessário (verificação de ano)
    if data_max < data_inicial.replace(year=data_max.year):
        anos_diff -= 1
    
    return anos_diff

In [7]:

# Aplicando a função na DataFrame
df['idade_ajustada'] = df.apply(ajustar_idade, axis=1)

C:\Users\Rafael\AppData\Local\Temp\ipykernel_11324\2339820722.py:3: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data_max = pd.to_datetime(row['fim'])
C:\Users\Rafael\AppData\Local\Temp\ipykernel_11324\2339820722.py:4: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data_inicial = pd.to_datetime(row['inicio'])

ValueError: day is out of range for month